# Generated by Django 3.1.13 on 2022-06-23 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews_manager', '0020_predictionreview'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('annotation_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews_manager.clinicalannotationstep')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
